apiVersion: v1
kind: Service
metadata:
  name: full-stack-service
spec:
  type: LoadBalancer
  selector:
    app: full-stack-app
  ports:
    - name: http
      port: 8089        # External port
      targetPort: 8080  # Container port (matches app)

