apiVersion: v1
kind: Service
metadata:
  name: full-stack-service
spec:
  type: LoadBalancer
  selector:
    app: full-stack-app
  ports:
    - name: http
      port: 80           # Publicly exposed port
      targetPort: 8080   # Port your app is running on inside container
